[package]
name = "crean"
version = "0.1.0"
authors = ["Trikzon <trikzondev@gmail.com>"]
edition = "2018"

[dependencies]
glfw = "0.41"
raw_gl = { package = "gl", version = "0.14" }

bitflags = "1.2"
thiserror = "1.0"